Repository livekit/livekit, pull requests merged in 2025-08, with the labels that each got.

#3885 handle frame number wrap back in svc
  .github/workflows/slack-notifier.yaml
  pkg/sfu/buffer/buffer.go
  pkg/sfu/buffer/dependencydescriptorparser.go
  pkg/sfu/utils/wraparound.go
  pkg/sfu/videolayerselector/dependencydescriptor.go
  pkg/sfu/videolayerselector/framenumberwrapper.go
Labels: slack-ts:cs-devs:1756457137.028419

#3888 Use departure timeout from room preset.
  pkg/service/roomallocator.go
Labels: slack-ts:cs-devs:1756485761.157589

#3889 Do not advertise NACK for RED.
  pkg/rtc/transport.go
Labels: slack-ts:cs-devs:1756554660.374069

#3891 Prevent race in determining BWE type.
  pkg/sfu/downtrack.go
Labels: slack-ts:cs-devs:1756568443.606919
