Repository livekit/livekit, pull requests merged in 2025-09, with the labels that each got.

#3903 Use gzip reader pool
  pkg/service/rtcservice.go
Labels: slack-ts:cs-devs:1757223336.896339

#3908 Refactor subscribedTrack + mediaTrackSubscriptions.
  pkg/routing/localrouter.go
  pkg/rtc/mediatrack.go
  pkg/rtc/mediatracksubscriptions.go
  pkg/rtc/subscribedtrack.go
  pkg/service/roommanager.go
  pkg/sfu/downtrack.go
Labels: slack-ts:cs-devs:1757334752.902429

#3925 Simulcast audio fixes
  pkg/rtc/mediaengine.go
  pkg/rtc/mediatrackreceiver.go
  pkg/rtc/mediatracksubscriptions.go
  pkg/rtc/participant.go
  pkg/rtc/participant_internal_test.go
  pkg/rtc/participant_sdp.go
  pkg/rtc/subscribedtrack.go
  pkg/rtc/utils.go
  pkg/rtc/wrappedreceiver.go
  pkg/sfu/buffer/buffer.go
  pkg/sfu/mime/mimetype.go
Labels: slack-ts:cs-devs:1757822733.021939

#3926 Fix dynacast subscriber node clearing on move participant.
  pkg/rtc/participant.go
Labels: slack-ts:cs-devs:1757843032.172779

#3934 More debugging of DD jump
  pkg/sfu/buffer/dependencydescriptorparser.go
Labels: slack-ts:cs-devs:1758225360.997339

#3935 Do DD restart only if DD structure is present.
  pkg/sfu/buffer/dependencydescriptorparser.go
Labels: slack-ts:cs-devs:1758228828.981899

#3936 Use difference in key frame counter to stop seeder.
  pkg/sfu/buffer/buffer.go
Labels: slack-ts:cs-devs:1758268603.737989

#3943 Use microseconds for forwarding stats.
  pkg/sfu/forwardstats.go
  pkg/sfu/receiver.go
Labels: slack-ts:cs-devs:1758574397.958259

#3948 handle terminated job requests
  pkg/agent/worker.go
  pkg/service/agentservice.go
Labels: slack-ts:cs-devs:1758676182.810959

#3949 Switch ops queue a singly linked list.
  pkg/utils/opsqueue.go
Labels: slack-ts:cs-devs:1758699434.705069

#3950 Revert "Switch ops queue a singly linked list."
  pkg/utils/opsqueue.go
Labels: slack-ts:cs-devs:1758702963.509349

#3951 Adjust stream allocator ping interval based on state.
  pkg/sfu/streamallocator/streamallocator.go
  pkg/sfu/streamallocator/track.go
  pkg/utils/opsqueue.go
Labels: slack-ts:cs-devs:1758703476.959529

#3956 Adjust for hold time when fowarding RTCP report.
  pkg/rtc/participant.go
  pkg/sfu/rtpstats/rtpstats_base.go
  pkg/sfu/rtpstats/rtpstats_receiver.go
  pkg/sfu/rtpstats/rtpstats_sender.go
  pkg/sfu/utils/owd_estimator.go
Labels: slack-ts:cs-devs:1758891679.708489

#3958 avoid logging on small values
  pkg/sfu/forwardstats.go
Labels: slack-ts:cs-devs:1759036262.698619

#3960 Add node_ip to config-sample.yaml
  config-sample.yaml
Labels: slack-ts:cs-devs:1759054611.720209

#3969 Update deps to fix redis issue when 1 cluster address is provided
  go.mod
  go.sum
Labels: slack-ts:cs-devs:1759203270.861719

#3970 Revert unintentional change to not handle transport fallback on
  pkg/rtc/transportmanager.go
  pkg/service/wire_gen.go
  pkg/sfu/rtpstats/rtpstats_base.go
Labels: slack-ts:cs-devs:1759207879.351999
