Repository livekit/livekit, pull requests merged in 2025-10, with the labels that each got.

#3984 Use padding only packets for dummy start of audio.
  pkg/sfu/downtrack.go
Labels: slack-ts:cs-devs:1759728442.546839

#3986 Support Opus mixed with RED when encrypted.
  pkg/rtc/subscribedtrack.go
  pkg/rtc/wrappedreceiver.go
  pkg/sfu/downtrack.go
Labels: slack-ts:cs-devs:1759833447.507769

#3987 Allow passing inline trunk for outbound calls.
  pkg/service/sip.go
Labels: slack-ts:telephony-devs:1759844516.566689

#3988 Limit check to red + opus when looking for primary codec match.
  pkg/sfu/downtrack.go
Labels: slack-ts:cs-devs:1759854174.778209

#3989 Increment RTP timestamp on padding when using dummy start.
  pkg/sfu/downtrack.go
  pkg/sfu/forwarder.go
  pkg/sfu/forwarder_test.go
  pkg/sfu/rtpmunger.go
Labels: slack-ts:cs-devs:1759859574.628099
